AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Enabled: false

# Style/HashSyntax:
#   EnforcedStyle: hash_rockets

inherit_from: .rubocop_todo.yml
