AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/MethodLength:
  Max: 40

# Style/HashSyntax:
#   EnforcedStyle: hash_rockets

inherit_from: .rubocop_todo.yml
